blank_issues_enabled: false
contact_links:
  - name: Project Documentation
    url: https://github.com/bobgit18/finops-cost-recom-engine/README.md
    about: Refer to the project documentation for guidance.
